# Preprocesamiento

1. Cargar datos y parsear timestamps

2. Detectar gaps > 60 segundos y marcar segmento_id

3. Remuestrear a 1 minuto DENTRO de cada segmento
   - continuas: mean
   - digitales: mode
   - caudal: sum
   - NO se imputan huecos entre segmentos
   - cada segmento se remuestrea independientemente

4. Descartar segmentos menores a 10 minutos
   - muy cortos para generar ventanas útiles

5. Identificar régimen operacional
   - regimen 0: apagado
   - regimen 1: sin carga
   - regimen 2: bajo carga

6. Filtrar → conservar regimen 1 y 2

7. Renumerar sesiones operacionales continuas
   - puede haber más sesiones que segmentos
   - un segmento puede contener varios cambios de régimen

8. Guardar en data/processed/operacional.parquet

In [94]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf

sns.set_style('whitegrid')

ANALOG_COLS  = ['TP2', 'TP3', 'H1', 'DV_pressure', 'Reservoirs',
                'Oil_temperature', 'Motor_current', 'Caudal_impulses']
BINARY_COLS  = ['COMP', 'DV_eletric', 'Towers', 'MPG', 'LPS',
                'Pressure_switch', 'Oil_level']

# 1. Cargar datos y parsear timestamps

In [95]:
datos = pd.read_csv('../data/raw/MetroPT3(AirCompressor).csv',
                parse_dates=['timestamp'])
datos.drop(columns=['Unnamed: 0'], inplace=True)
df = datos.sort_values('timestamp').reset_index(drop = True)
df.head()

,timestamp,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Motor_current,COMP,DV_eletric,Towers,MPG,LPS,Pressure_switch,Oil_level,Caudal_impulses
0,2020-02-01 00:00:00,-0.012,9.358,9.340,-0.024,9.358,53.600,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
1,2020-02-01 00:00:10,-0.014,9.348,9.332,-0.022,9.348,53.675,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
2,2020-02-01 00:00:19,-0.012,9.338,9.322,-0.022,9.338,53.600,0.0425,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
3,2020-02-01 00:00:29,-0.012,9.328,9.312,-0.022,9.328,53.425,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
4,2020-02-01 00:00:39,-0.012,9.318,9.302,-0.022,9.318,53.475,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0

# 2. Detectar gaps grandes y marcar límites de sesión

#### Verificar fracuencia real (aparentemente son 10 segundos)

In [96]:
diferencias = df['timestamp'].diff().dt.total_seconds()

print('Frecuencia predominante (segundos):')
print(diferencias.value_counts().head(10))

print("\nGaps mayores a 30 segundos:")
print((diferencias > 30).sum())

print(f'\nGap maximo {diferencias.max():.0f} segundos')
print(f'Gap máximo {diferencias.max()/60:.0f} minutos')
print(f'Gap máximo {diferencias.max()/3600:.0f} horas')

Frecuencia predominante (segundos):
timestamp
10.0    1337521
9.0      128277
12.0      38321
13.0       7988
11.0       4471
21.0         10
19.0          5
22.0          4
20.0          3
17.0          3
Name: count, dtype: int64

Gaps mayores a 30 segundos:
331

Gap maximo 172918 segundos
Gap máximo 2882 minutos
Gap máximo 48 horas

#### Detectar gaps grandes antes de remeustrear

Cuando los gaps son grandes, significa que no fue un error de registro y si fue un paro de operación real y por lo tanto, el final de una sesión de uso.

Con lo anterior se puede ver que hay variaciónes de hasta 13 segundos que se pueden considerar como normales. (7988)

In [97]:
GAP_UMBRAL = 60 # segundos o 1 minuto
# La variación normal más grande es de 13 segundos.
# 1 minuto es como un intervalo de seguridad para esos 13 segundos

df['diff_segundos'] = df['timestamp'].diff().dt.total_seconds()
df['nuevo_segmento'] = (df['diff_segundos'] > GAP_UMBRAL)
df['id_segmento'] = df['nuevo_segmento'].cumsum()

print(f"Total de segmentos: {df['id_segmento'].nunique()}")
df.head(10)

Total de segmentos: 332

,timestamp,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Motor_current,COMP,DV_eletric,Towers,MPG,LPS,Pressure_switch,Oil_level,Caudal_impulses,diff_segundos,nuevo_segmento,id_segmento
0,2020-02-01 00:00:00,-0.012,9.358,9.340,-0.024,9.358,53.600,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,NaN,False,0
1,2020-02-01 00:00:10,-0.014,9.348,9.332,-0.022,9.348,53.675,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,10.0,False,0
2,2020-02-01 00:00:19,-0.012,9.338,9.322,-0.022,9.338,53.600,0.0425,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,9.0,False,0
3,2020-02-01 00:00:29,-0.012,9.328,9.312,-0.022,9.328,53.425,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,10.0,False,0
4,2020-02-01 00:00:39,-0.012,9.318,9.302,-0.022,9.318,53.475,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,10.0,False,0
5,2020-02-01 00:00:49,-0.012,9.306,9.290,-0.024,9.308,53.500,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,10.0,False,0
6,2020-02-01 00:00:59,-0.012,9.296,9.280,-0.024,9.298,53.375,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,10.0,False,0
7,2020-02-01 00:01:09,-0.014,9.286,9.270,-0.024,9.286,53.550,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,10.0,False,0
8,2020-02-01 00:01:19,-0.012,9.276,9.258,-0.022,9.276,53.425,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,10.0,False,0
9,2020-02-01 00:01:29,-0.012,9.264,9.248,-0.022,9.264,53.375,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,10.0,False,0

In [98]:
tamaños = df.groupby('id_segmento').size()*10/60 # en minutos
print(tamaños.head())

print('\nTamaño de los segmentos (minutos)')
print(tamaños.describe())

print('\nSegmentos menores a 10 minutos')
print(f'{(tamaños < 10).sum()}')

print('\nSegmentos mayores a 60 minutos')
print(f'{(tamaños > 60).sum()}')

print('\nSegmentos mayroes a 6 hroas')
print(f'{(tamaños > 360).sum()}')

id_segmento
0     775.666667
1     410.000000
2       5.000000
3     185.000000
4    3925.000000
dtype: float64

Tamaño de los segmentos (minutos)
count     332.000000
mean      761.520080
std       957.510374
min         4.833333
25%        25.000000
50%       389.833333
75%      1205.000000
max      6099.833333
dtype: float64

Segmentos menores a 10 minutos
41

Segmentos mayores a 60 minutos
213

Segmentos mayroes a 6 hroas
170

De los 332 segmentos:

| Métrica | Valor | Equivalencia |
|---------|-------|---------------|
| **Media** | 761 min | ≈ 12.7 h |
| **Mínimo** | 4.8 min | ≈ 5 min |
| **Máximo** | 6099 min | ≈ 101 h (4.2 días) |



- **25%** de los segmentos duraron **≤ 25 minutos**
- **50%** (mediana) duraron **≤ 389.8 minutos** (≈ 6.5 h)
- **75%** duraron **≤ 1205 minutos** (≈ 20 h)



| Condición | N° segmentos | Destino |
|-----------|--------------|---------|
| **< 10 minutos** | 41 | Descartar porque son muy poquitos |
| **> 60 minutos** | 213 | Dicen muy poco |
| **> 6 horas (360 min)** | 170 | **Núcleo para entrenar** |

El dataset contiene 332 segmentos continuos. 170 segmentos tienen duración mayor a 6 horas y concentran la mayor parte de los datos útiles para entrenamiento. Los 41 segmentos menores  a 10 minutos van a tener que ser descartados porque no permiten la construcción de ventanas deslizantes válidas.

#### Las fallas caen en los segmentos grandes?

In [99]:
fallas = [
    '2020-04-18 00:00',
    '2020-05-29 23:30',
    '2020-06-05 10:00',
    '2020-07-15 14:30'
    ]

for falla in fallas:
    ts = pd.Timestamp(falla)
    segmento = df[df['timestamp'] <= ts]['id_segmento'].iloc[-1]
    duracion = tamaños[segmento]
    print(f'\nFalla {falla} --- Segmento {segmento} -- Duración {duracion:.0f} min')

Falla 2020-04-18 00:00 --- Segmento 112 -- Duración 1029 min

Falla 2020-05-29 23:30 --- Segmento 181 -- Duración 1645 min

Falla 2020-06-05 10:00 --- Segmento 191 -- Duración 4028 min

Falla 2020-07-15 14:30 --- Segmento 252 -- Duración 1205 min

# 3. Remuestrear a 1 minuto dentro de cada segmento

Voy a pasar de un dataframe conuna frecuencia irregular aproximada de 10 segundos a otra de un minuto exacto utilizando en las variables modas, medias y una suma

In [100]:
agg_func = {
    # Analógicas → promedio del minuto
    'TP2':              'mean',
    'TP3':              'mean',
    'H1':               'mean',
    'DV_pressure':      'mean',
    'Reservoirs':       'mean',
    'Oil_temperature':  'mean',
    'Motor_current':    'mean',
    # Digitales → valor más frecuente del minuto
    'COMP':             lambda x: x.mode()[0],
    'DV_eletric':       lambda x: x.mode()[0],
    'Towers':           lambda x: x.mode()[0],
    'MPG':              lambda x: x.mode()[0],
    'LPS':              lambda x: x.mode()[0],
    'Pressure_switch':  lambda x: x.mode()[0],
    'Oil_level':        lambda x: x.mode()[0],
    # Caudal → suma de pulsos en el minuto
    'Caudal_impulses':  'sum',
}

In [101]:
# id, df de ese id
for seg_id, grupo in df.groupby('id_segmento'):
    print(f"EL segmento es: {seg_id}")
    print(f"El df de ese segmento dura: {len(grupo)*10/60:.0f} min")
    print(grupo.head())

EL segmento es: 0
El df de ese segmento dura: 776 min
            timestamp    TP2    TP3     H1  DV_pressure  Reservoirs  \
0 2020-02-01 00:00:00 -0.012  9.358  9.340       -0.024       9.358
1 2020-02-01 00:00:10 -0.014  9.348  9.332       -0.022       9.348
2 2020-02-01 00:00:19 -0.012  9.338  9.322       -0.022       9.338
3 2020-02-01 00:00:29 -0.012  9.328  9.312       -0.022       9.328
4 2020-02-01 00:00:39 -0.012  9.318  9.302       -0.022       9.318

   Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  LPS  \
0           53.600         0.0400   1.0         0.0     1.0  1.0  0.0
1           53.675         0.0400   1.0         0.0     1.0  1.0  0.0
2           53.600         0.0425   1.0         0.0     1.0  1.0  0.0
3           53.425         0.0400   1.0         0.0     1.0  1.0  0.0
4           53.475         0.0400   1.0         0.0     1.0  1.0  0.0

   Pressure_switch  Oil_level  Caudal_impulses  diff_segundos  nuevo_segmento  \
0              1.0        1.0              1.0            NaN           False
1              1.0        1.0              1.0           10.0           False
2              1.0        1.0              1.0            9.0           False
3              1.0        1.0              1.0           10.0           False
4              1.0        1.0              1.0           10.0           False

   id_segmento
0            0
1            0
2            0
3            0
4            0
EL segmento es: 1
El df de ese segmento dura: 410 min
               timestamp    TP2    TP3     H1  DV_pressure  Reservoirs  \
4654 2020-02-01 12:53:47 -0.012  9.124  9.108       -0.012       9.130
4655 2020-02-01 12:53:57 -0.010  9.116  9.102       -0.012       9.122
4656 2020-02-01 12:54:07 -0.010  9.106  9.090       -0.012       9.112
4657 2020-02-01 12:54:17 -0.012  9.096  9.080       -0.012       9.100
4658 2020-02-01 12:54:27 -0.012  9.086  9.072       -0.012       9.090

      Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  LPS  \
4654           59.675         0.0375   1.0         0.0     1.0  1.0  0.0
4655           59.750         0.0350   1.0         0.0     1.0  1.0  0.0
4656           59.675         0.0375   1.0         0.0     1.0  1.0  0.0
4657           59.700         0.0375   1.0         0.0     1.0  1.0  0.0
4658           59.650         0.0375   1.0         0.0     1.0  1.0  0.0

      Pressure_switch  Oil_level  Caudal_impulses  diff_segundos  \
4654              1.0        1.0              1.0          307.0
4655              1.0        1.0              1.0           10.0
4656              1.0        1.0              1.0           10.0
4657              1.0        1.0              1.0           10.0
4658              1.0        1.0              1.0           10.0

      nuevo_segmento  id_segmento
4654            True            1
4655           False            1
4656           False            1
4657           False            1
4658           False            1
EL segmento es: 2
El df de ese segmento dura: 5 min
               timestamp    TP2    TP3     H1  DV_pressure  Reservoirs  \
7114 2020-02-01 23:15:33 -0.018  9.990  9.980       -0.022       9.992
7115 2020-02-01 23:15:43 -0.014  9.968  9.956       -0.022       9.968
7116 2020-02-01 23:15:53 -0.012  9.950  9.938       -0.022       9.950
7117 2020-02-01 23:16:03 -0.014  9.932  9.918       -0.022       9.930
7118 2020-02-01 23:16:13 -0.012  9.914  9.902       -0.022       9.916

      Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  LPS  \
7114           44.850         3.9700   1.0         0.0     1.0  1.0  0.0
7115           45.675         3.9650   1.0         0.0     1.0  1.0  0.0
7116           46.325         4.0525   1.0         0.0     1.0  1.0  0.0
7117           47.100         4.0450   1.0         0.0     1.0  1.0  0.0
7118           47.500         4.0225   1.0         0.0     1.0  1.0  0.0

      Pressure_switch  Oil_level  Caudal_impulses  diff_segundos  \
7114              1.0        1.0              1.0        12929.0
7115              1.0        1.0              1.0           10.0
7116              1.0        1.0              1.0           10.0
7117              1.0        1.0              1.0           10.0
7118              1.0        1.0              1.0           10.0

      nuevo_segmento  id_segmento
7114            True            2
7115           False            2
7116           False            2
7117           False            2
7118           False            2
EL segmento es: 3
El df de ese segmento dura: 185 min
               timestamp     TP2     TP3      H1  DV_pressure  Reservoirs  \
7144 2020-02-02 04:34:27   9.952   9.630  -0.012       -0.024       9.630
7145 2020-02-02 04:34:37  10.164   9.848  -0.012       -0.024       9.848
7146 2020-02-02 04:34:47  10.372  10.058  -0.012       -0.026      10.058
7147 2020-02-02 04:34:57  -0.026  10.078  10.076       -0.024      10.080
7148 2020-02-02 04:35:07  -0.024  10.028  10.024       -0.024      10.028

      Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  LPS  \
7144           31.975         6.2750   0.0         1.0     0.0  0.0  0.0
7145           32.675         6.2425   0.0         1.0     0.0  0.0  0.0
7146           33.275         6.2625   0.0         1.0     0.0  0.0  0.0
7147           33.925         4.0000   1.0         0.0     1.0  1.0  0.0
7148           35.000         3.9625   1.0         0.0     1.0  1.0  0.0

      Pressure_switch  Oil_level  Caudal_impulses  diff_segundos  \
7144              1.0        1.0              1.0        18846.0
7145              1.0        1.0              1.0           10.0
7146              1.0        1.0              1.0           10.0
7147              1.0        1.0              1.0           10.0
7148              1.0        1.0              1.0           10.0

      nuevo_segmento  id_segmento
7144            True            3
7145           False            3
7146           False            3
7147           False            3
7148           False            3
EL segmento es: 4
El df de ese segmento dura: 3925 min
               timestamp    TP2    TP3     H1  DV_pressure  Reservoirs  \
8254 2020-02-02 07:41:52 -0.012  8.310  8.294       -0.022       8.312
8255 2020-02-02 07:42:02 -0.014  8.304  8.290       -0.022       8.306
8256 2020-02-02 07:42:12 -0.014  8.298  8.284       -0.024       8.302
8257 2020-02-02 07:42:22 -0.014  8.296  8.280       -0.020       8.298
8258 2020-02-02 07:42:31 -0.014  8.288  8.274       -0.024       8.292

      Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  LPS  \
8254            53.10         3.8125   1.0         0.0     1.0  1.0  0.0
8255            53.15         3.8125   1.0         0.0     1.0  1.0  0.0
8256            53.05         3.8475   1.0         0.0     1.0  1.0  0.0
8257            53.20         3.7625   1.0         0.0     1.0  1.0  0.0
8258            53.20         3.7225   1.0         0.0     1.0  1.0  0.0

      Pressure_switch  Oil_level  Caudal_impulses  diff_segundos  \
8254              1.0        1.0              1.0          252.0
8255              1.0        1.0              1.0           10.0
8256              1.0        1.0              1.0           10.0
8257              1.0        1.0              1.0           10.0
8258              1.0        1.0              1.0            9.0

      nuevo_segmento  id_segmento
8254            True            4
8255           False            4
8256           False            4
8257           False            4
8258           False            4
EL segmento es: 5
El df de ese segmento dura: 25 min
                timestamp     TP2     TP3      H1  DV_pressure  Reservoirs  \
31804 2020-02-05 00:43:00  10.412  10.032  -0.012       -0.022      10.030
31805 2020-02-05 00:43:10  -0.022  10.120  10.120       -0.018      10.120
31806 2020-02-05 00:43:20  -0.024  10.070  10.066       -0.022      10.070
31807 2020-02-05 00:43:30  -0.020  10.034  10.028       -0.022      10.034
31808 2020-02-05 00:43:40  -0.020  10.000   9.992       -0.020      10.000

       Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  LPS  \
31804           56.600         6.3325   0.0         1.0     1.0  0.0  0.0
31805           56.975         4.1025   1.0         0.0     1.0  1.0  0.0
31806           57.525         3.9450   1.0         0.0     1.0  1.0  0.0
31807           57.900         4.0200   1.0         0.0     1.0  1.0  0.0
31808           58.500         3.9475   1.0         0.0     1.0  1.0  0.0

       Pressure_switch  Oil_level  Caudal_impulses  diff_segundos  \
31804              1.0        1.0              1.0          639.0
31805              1.0        1.0              1.0           10.0
31806              1.0        1.0              1.0           10.0
31807              1.0        1.0              1.0           10.0
31808              1.0        1.0              1.0           10.0

       nuevo_segmento  id_segmento
31804            True            5
31805           False            5
31806           False            5
31807           False            5
31808           False            5
EL segmento es: 6
El df de ese segmento dura: 1310 min
                timestamp    TP2     TP3      H1  DV_pressure  Reservoirs  \
31954 2020-02-05 04:28:42 -0.024  10.122  10.122       -0.022      10.122
31955 2020-02-05 04:28:51 -0.022  10.078  10.074       -0.022      10.078
31956 2020-02-05 04:29:01 -0.018  10.044  10.038       -0.020      10.046
31957 2020-02-05 04:29:11 -0.016  10.014  10.004       -0.022      10.014
31958 2020-02-05 04:29:21 -0.016   9.988   9.976       -0.022       9.990

       Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  LPS  \
31954           42.250         3.8725   1.0         0.0     1.0  1.0  0.0
31955           43.225         3.8375   1.0         0.0     1.0  1.0  0.0
31956           44.125         3.9450   1.0         0.0     1.0  1.0  0.0
31957           44.950         3.9600   1.0         0.0     1.0  1.0  0.0
31958           45.825         3.9975   1.0         0.0     1.0  1.0  0.0

       Pressure_switch  Oil_level  Caudal_impulses  diff_segundos  \
31954              1.0        1.0              1.0        12065.0
31955              1.0        1.0              1.0            9.0
31956              1.0        1.0              1.0           10.0
31957              1.0        1.0              1.0           10.0
31958              1.0        1.0              1.0           10.0

       nuevo_segmento  id_segmento
31954            True            6
31955           False            6
31956           False            6
31957           False            6
31958           False            6
EL segmento es: 7
El df de ese segmento dura: 380 min
                timestamp    TP2    TP3    H1  DV_pressure  Reservoirs  \
39814 2020-02-06 07:52:21  7.768  7.436 -0.01       -0.022       7.442
39815 2020-02-06 07:52:30  7.992  7.680 -0.01       -0.020       7.672
39816 2020-02-06 07:52:40  8.230  7.912 -0.01       -0.022       7.914
39817 2020-02-06 07:52:50  8.498  8.068 -0.01       -0.022       8.068
39818 2020-02-06 07:53:00  8.696  8.286 -0.01       -0.020       8.286

       Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  LPS  \
39814           35.275         5.6925   0.0         1.0     0.0  0.0  1.0
39815           35.675         5.8400   0.0         1.0     0.0  0.0  0.0
39816           35.950         5.9125   0.0         1.0     0.0  0.0  0.0
39817           36.475         5.8800   0.0         1.0     1.0  0.0  0.0
39818           36.875         5.9650   0.0         1.0     1.0  0.0  0.0

       Pressure_switch  Oil_level  Caudal_impulses  diff_segundos  \
39814              1.0        1.0              1.0        20720.0
39815              1.0        1.0              1.0            9.0
39816              1.0        1.0              1.0           10.0
39817              1.0        1.0              1.0           10.0
39818              1.0        1.0              1.0           10.0

       nuevo_segmento  id_segmento
39814            True            7
39815           False            7
39816           False            7
39817           False            7
39818           False            7
EL segmento es: 8
El df de ese segmento dura: 300 min
                timestamp    TP2    TP3     H1  DV_pressure  Reservoirs  \
42094 2020-02-06 14:19:23 -0.008  8.550  8.536       -0.016       8.554
42095 2020-02-06 14:19:33 -0.012  8.526  8.512       -0.014       8.530
42096 2020-02-06 14:19:42 -0.010  8.494  8.478       -0.014       8.498
42097 2020-02-06 14:19:52 -0.008  8.466  8.450       -0.016       8.470
42098 2020-02-06 14:20:02 -0.010  8.460  8.446       -0.016       8.464

       Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  LPS  \
42094           59.325         3.9375   1.0         0.0     1.0  1.0  0.0
42095           59.300         3.9075   1.0         0.0     1.0  1.0  0.0
42096           59.375         3.9375   1.0         0.0     1.0  1.0  0.0
42097           59.475         0.0400   1.0         0.0     1.0  1.0  0.0
42098           59.625         0.0400   1.0         0.0     1.0  1.0  0.0

       Pressure_switch  Oil_level  Caudal_impulses  diff_segundos  \
42094              1.0        1.0              1.0          630.0
42095              1.0        1.0              1.0           10.0
42096              1.0        1.0              1.0            9.0
42097              1.0        1.0              1.0           10.0
42098              1.0        1.0              1.0           10.0

       nuevo_segmento  id_segmento
42094            True            8
42095           False            8
42096           False            8
42097           False            8
42098           False            8
EL segmento es: 9
El df de ese segmento dura: 15 min
                timestamp     TP2     TP3      H1  DV_pressure  Reservoirs  \
43894 2020-02-06 23:33:19  10.174   9.896  -0.008       -0.020       9.896
43895 2020-02-06 23:33:29  10.374  10.100  -0.010       -0.020      10.098
43896 2020-02-06 23:33:39  -0.022  10.158  10.158       -0.016      10.160
43897 2020-02-06 23:33:49  -0.020  10.110  10.106       -0.018      10.108
43898 2020-02-06 23:33:59  -0.018  10.068  10.062       -0.020      10.066

       Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  LPS  \
43894           43.350         6.2650   0.0         1.0     0.0  0.0  0.0
43895           43.850         6.3550   0.0         1.0     0.0  0.0  0.0
43896           44.225         4.0275   1.0         0.0     1.0  1.0  0.0
43897           45.125         3.9700   1.0         0.0     1.0  1.0  0.0
43898           46.475         3.9550   1.0         0.0     1.0  1.0  0.0

       Pressure_switch  Oil_level  Caudal_impulses  diff_segundos  \
43894              1.0        1.0              1.0        15404.0
43895              1.0        1.0              1.0           10.0
43896              1.0        1.0              1.0           10.0
43897              1.0        1.0              1.0           10.0
43898              1.0        1.0              1.0           10.0

       nuevo_segmento  id_segmento
43894            True            9
43895           False            9
43896           False            9
43897           False            9
43898           False            9
EL segmento es: 10
El df de ese segmento dura: 740 min
                timestamp     TP2     TP3      H1  DV_pressure  Reservoirs  \
43984 2020-02-07 04:28:13  10.246   9.956  -0.010       -0.018       9.960
43985 2020-02-07 04:28:23  10.452  10.164  -0.008       -0.020      10.168
43986 2020-02-07 04:28:33  -0.024  10.134  10.134       -0.020      10.136
43987 2020-02-07 04:28:43  -0.022  10.092  10.088       -0.020      10.096
43988 2020-02-07 04:28:53  -0.020  10.056  10.048       -0.022      10.056

       Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  LPS  \
43984           37.725         6.2775   0.0         1.0     0.0  0.0  0.0
43985           38.250         6.3875   0.0         1.0     0.0  0.0  0.0
43986           38.675         3.8875   1.0         0.0     1.0  1.0  0.0
43987           39.875         3.9175   1.0         0.0     1.0  1.0  0.0
43988           41.275         4.0000   1.0         0.0     1.0  1.0  0.0

       Pressure_switch  Oil_level  Caudal_impulses  diff_segundos  \
43984              1.0        1.0              1.0        16811.0
43985              1.0        1.0              1.0           10.0
43986              1.0        1.0              1.0           10.0
43987              1.0        1.0              1.0           10.0
43988              1.0        1.0              1.0           10.0

       nuevo_segmento  id_segmento
43984            True           10
43985           False           10
43986           False           10
43987           False           10
43988           False           10
EL segmento es: 11
El df de ese segmento dura: 540 min
                timestamp    TP2    TP3     H1  DV_pressure  Reservoirs  \
48424 2020-02-07 16:48:31 -0.006  9.130  9.116       -0.012       9.132
48425 2020-02-07 16:48:41 -0.008  9.122  9.106       -0.010       9.124
48426 2020-02-07 16:48:51 -0.008  9.114  9.100       -0.012       9.116
48427 2020-02-07 16:49:00 -0.008  9.106  9.090       -0.012       9.108
48428 2020-02-07 16:49:10 -0.008  9.098  9.084       -0.012       9.100

       Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  LPS  \
48424           62.075         3.7000   1.0         0.0     1.0  1.0  0.0
48425           62.150         3.7025   1.0         0.0     1.0  1.0  0.0
48426           61.975         3.7175   1.0         0.0     1.0  1.0  0.0
48427           62.175         3.7125   1.0         0.0     1.0  1.0  0.0
48428           62.075         3.6950   1.0         0.0     1.0  1.0  0.0

       Pressure_switch  Oil_level  Caudal_impulses  diff_segundos  \
48424              1.0        1.0              1.0          413.0
48425              1.0        1.0              1.0           10.0
48426              1.0        1.0              1.0           10.0
48427              1.0        1.0              1.0            9.0
48428              1.0        1.0              1.0           10.0

       nuevo_segmento  id_segmento
48424            True           11
48425           False           11
48426           False           11
48427           False           11
48428           False           11
EL segmento es: 12
El df de ese segmento dura: 1375 min
                timestamp    TP2    TP3     H1  DV_pressure  Reservoirs  \
51664 2020-02-08 01:48:25 -0.010  8.090  8.076       -0.018       8.090
51665 2020-02-08 01:48:34 -0.010  8.082  8.068       -0.018       8.082
51666 2020-02-08 01:48:44 -0.012  8.074  8.058       -0.018       8.072
51667 2020-02-08 01:48:54 -0.010  8.056  5.130       -0.018       8.054
51668 2020-02-08 01:49:04  8.392  8.060 -0.020       -0.020       8.060

       Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  LPS  \
51664           53.325         3.7950   1.0         0.0     1.0  1.0  0.0
51665           53.225         3.7825   1.0         0.0     1.0  1.0  0.0
51666           53.300         3.7250   1.0         0.0     1.0  1.0  0.0
51667           53.400         3.8575   0.0         1.0     0.0  0.0  0.0
51668           53.225         5.8425   0.0         1.0     0.0  0.0  0.0

       Pressure_switch  Oil_level  Caudal_impulses  diff_segundos  \
51664              1.0        1.0              1.0          288.0
51665              1.0        1.0              1.0            9.0
51666              1.0        1.0              1.0           10.0
51667              1.0        1.0              1.0           10.0
51668              1.0        1.0              1.0           10.0

       nuevo_segmento  id_segmento
51664            True           12
51665           False           12
51666           False           12
51667           False           12

# 4. Descartar segmentos menores a 10 minutos

In [ ]:
segmentos_resampleados = []
for id_segmento, grupo in df.groupby('id_segmento'):

    if len(grupo) < 60:
        continue

    grupo = grupo.set_index('timestamp')

    resampled = grupo.resample('1min').agg(agg_func)
    resampled = resampled.dropna()

    resampled['id_segmento'] = id_segmento
    segmentos_resampleados.append(resampled)

In [ ]:
print(len(segmentos_resampleados))
df_min = pd.concat(segmentos_resampleados).reset_index()
print(f"filas   : {df_min.shape[0]}")
print(f"columnas: {df_min.shape[1]}")
df_min.head()

291
filas   : 252473
columnas: 17

,timestamp,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Motor_current,COMP,DV_eletric,Towers,MPG,LPS,Pressure_switch,Oil_level,Caudal_impulses,id_segmento
0,2020-02-01 00:00:00,-0.012286,9.327429,9.311143,-0.022857,9.328000,53.521429,0.040357,1.0,0.0,1.0,1.0,0.0,1.0,1.0,7.0,0
1,2020-02-01 00:01:00,-0.013000,9.260000,9.243333,-0.023333,9.259667,53.420833,0.040000,1.0,0.0,1.0,1.0,0.0,1.0,1.0,6.0,0
2,2020-02-01 00:02:00,-0.012667,9.198333,9.182000,-0.022333,9.199000,53.325000,0.040000,1.0,0.0,1.0,1.0,0.0,1.0,1.0,6.0,0
3,2020-02-01 00:03:00,-0.012333,9.136667,9.120667,-0.022667,9.136667,53.200000,0.040000,1.0,0.0,1.0,1.0,0.0,1.0,1.0,6.0,0
4,2020-02-01 00:04:00,-0.013000,9.075667,9.060000,-0.023000,9.075667,53.129167,0.040000,1.0,0.0,1.0,1.0,0.0,1.0,1.0,6.0,0

In [ ]:
print(f"Registros originales:         {len(df):,}")
print(f"Registros a 1 minuto:         {len(df_min):,}")
print(f"Factor de reducción:          {len(df)/len(df_min):.1f}x")
print(f"Segmentos conservados:        {df_min['id_segmento'].nunique()}")
print(f"Segmentos descartados (<10m): {df['id_segmento'].nunique() - df_min['id_segmento'].nunique()}")

Registros originales:         1,516,948
Registros a 1 minuto:         252,473
Factor de reducción:          6.0x
Segmentos conservados:        291
Segmentos descartados (<10m): 41

las fallas siguen presentes?

In [ ]:
for falla in fallas:
    ts = pd.Timestamp(falla)
    presente = (df_min['timestamp'] <= ts).any()
    print(f"falla {falla} presente en df_ min: {presente}")

falla 2020-04-18 00:00 presente en df_ min: True
falla 2020-05-29 23:30 presente en df_ min: True
falla 2020-06-05 10:00 presente en df_ min: True
falla 2020-07-15 14:30 presente en df_ min: True

# 5. Identificar régimen operacional

#### > Régimenes de operación.
| Estado          | COMP | DV_electric | MPG | LPS                       | Motor_current |
|----------------|------|-------------|-----|---------------------------|---------------|
| APAGADO        | 1    | 0           | 1   | 0 o 1 (depende presión residual) | ≈ 0 A         |
| SIN CARGA (offloaded) | 1    | 0           | 1   | —                        | ≈ 4 A         |
| BAJO CARGA (operación normal) | 0    | 1           | 0   | 0                        | ≈ 7 A         |

También tomar en cuenta 'Motor_current' > 2

In [ ]:
df_reg = df_min.copy()
df_reg['regimen'] = 0 # APAGADO
df_reg.loc[(df_reg['DV_eletric'] == 0) & (df_reg['Motor_current'] > 2), 'regimen'] = 1 # Sin carga
df_reg.loc[(df_reg['DV_eletric'] == 1) & (df_reg['Motor_current'] > 2), 'regimen'] = 2 # Con carga

df_reg.head()

,timestamp,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Motor_current,COMP,DV_eletric,Towers,MPG,LPS,Pressure_switch,Oil_level,Caudal_impulses,id_segmento,regimen
0,2020-02-01 00:00:00,-0.012286,9.327429,9.311143,-0.022857,9.328000,53.521429,0.040357,1.0,0.0,1.0,1.0,0.0,1.0,1.0,7.0,0,0
1,2020-02-01 00:01:00,-0.013000,9.260000,9.243333,-0.023333,9.259667,53.420833,0.040000,1.0,0.0,1.0,1.0,0.0,1.0,1.0,6.0,0,0
2,2020-02-01 00:02:00,-0.012667,9.198333,9.182000,-0.022333,9.199000,53.325000,0.040000,1.0,0.0,1.0,1.0,0.0,1.0,1.0,6.0,0,0
3,2020-02-01 00:03:00,-0.012333,9.136667,9.120667,-0.022667,9.136667,53.200000,0.040000,1.0,0.0,1.0,1.0,0.0,1.0,1.0,6.0,0,0
4,2020-02-01 00:04:00,-0.013000,9.075667,9.060000,-0.023000,9.075667,53.129167,0.040000,1.0,0.0,1.0,1.0,0.0,1.0,1.0,6.0,0,0

In [ ]:
df_reg['regimen'].value_counts()

regimen
0    137733
1     74587
2     40153
Name: count, dtype: int64

# 6. Filtrar y solo conservar regimen 1 y 2

In [ ]:
df_reg = df_reg[df_reg['regimen'] != 0].reset_index(drop=True)
df_reg.head()

,timestamp,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Motor_current,COMP,DV_eletric,Towers,MPG,LPS,Pressure_switch,Oil_level,Caudal_impulses,id_segmento,regimen
0,2020-02-01 00:23:00,7.468667,8.511667,1.282667,-0.023333,8.509667,49.712500,5.740833,0.0,1.0,0.0,0.0,0.0,1.0,1.0,6.0,0,2
1,2020-02-01 00:24:00,8.343000,9.773000,1.671333,-0.023000,9.769333,49.854167,5.814167,0.0,1.0,1.0,0.0,0.0,1.0,1.0,6.0,0,2
2,2020-02-01 00:25:00,-0.020000,9.978333,9.970333,-0.022333,9.977000,51.975000,3.881667,1.0,0.0,1.0,1.0,0.0,1.0,1.0,6.0,0,1
3,2020-02-01 00:26:00,-0.013333,9.860667,9.847000,-0.022667,9.860667,53.654167,3.865833,1.0,0.0,1.0,1.0,0.0,1.0,1.0,6.0,0,1
4,2020-02-01 00:27:00,-0.012000,9.781000,9.766000,-0.022333,9.781000,53.241667,3.876250,1.0,0.0,1.0,1.0,0.0,1.0,1.0,6.0,0,1